name: Publish docs

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '6.x'

      - name: Build ROCrates.Net
        run: >-
          dotnet build -c Release

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Build docs site
        run: docfx docs/docfx.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site