name: Version bump ROCrates.Net

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: Version tag
        required: true

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '6.x'

      - name: .NET project version updater
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: ROCrates.Net/ROCrates.Net.csproj
          version: ${{ github.event.inputs.version_tag }}

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0